### ISSUE TITLE
DOM replacement is visible for the end user

### ISSUE THREAD

**Issue by katysovas** [danmaz74/ABalytics#10]
More a question than an issue. It seems like it takes a split second to replace the text in the element. I put the code in the header before everything else, then it loads a page with the original DOM and then it replaces it. It's visible and glitchy for the end user. Is there a way to replace the code before the original DOM is loaded? How do VWO and Optimizely accomplish it? Thank you for the answer.

**Comment by luctus** [comment]
Why are you replacing the text? I'd try to put an empty element as the original DOM, changing this:

``` html
<div class="experiment1_class1_name">
  This content will be replaced by ABalytics
</div>
```

into this:

``` html
<div class="experiment1_class1_name"></div>
```

**Comment by lkraav** [comment]
@katysovas vwo and optimizely suffer from flicker effects just like any other DOM manipulation approach. It all boils down to how fast you can load everything and it what order. It's also possible to employ tricks like hiding everything by default and unhiding once manipulation is done.

**Comment by katysovas** [comment]
@luctus It's still an issue in my case, where the element is a button. So if I leave it blank, it renders a small size button with no text and then it adds a text to it after a second or so. I am testing it on Wordpress site, put all the code to the header. I am not sure how else could I speed it up..

**Comment by danmaz74** [comment]
@katysovas if you really hate the flickering effect, the only idea I have would be to add some sort of ajax loading animation before the experiment is rendered, and make it disappear only after that render. 

I'm not aware of any way to have no flicker at all with a client-only solution like this library.
