### ISSUE TITLE
How to set the substitution ratio/randomization.

### ISSUE THREAD

**Issue by barel22** [danmaz74/ABalytics#13]

**Comment by danmaz74** [comment]
It's not a parameter, but you can edit the code if you need.

**Comment by barelasaf** [comment]
Thanks
> On 15 Dec 2016, at 6:45 PM, Daniele Mazzini <notifications@github.com> wrote:
> 
> It's not a parameter, but you can edit the code if you need.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/danmaz74/ABalytics/issues/13#issuecomment-267377411 <https://github.com/danmaz74/ABalytics/issues/13#issuecomment-267377411>
AD
