### ISSUE TITLE
How to set goal?

### ISSUE THREAD

**Issue by leonho** [danmaz74/ABalytics#4]
Nice tool you made thanks! I want to test new UI components on a web app, instead of doing tuning on a single path funnel.

Are there any options when I have many links/actions on a page and I only want to measure specific action/clickthroughs as a conversion?

Thanks!

**Comment by danmaz74** [comment]
Hi. I didn't understand exactly what you want to do, but with google analytics you can create multiple goals, and track each of them individually vs. the different versions that you're testing with ABalytics. Does this answer your question?
