### ISSUE TITLE
Cannot add full html into the code because of the "

### ISSUE THREAD

**Issue by marscormier** [danmaz74/ABalytics#5]
I am trying to write something like

{
                name: 'ab_compel',
                "ab_test1": "This is one of the variations of our split test <br>< /img src="1.jpg">"
            },

since there is a " in the <img src> tag the script won't work.  Any workaround or solution?

**Comment by danmaz74** [comment]
Did you try substituting the double quotes with single quotes?  Example:

{
name: 'ab_compel',
"ab_test1": "This is one of the variations of our split test 
<--img src='1.jpg'><--/img>"
},

**Comment by donohoe** [comment]
Or you could use single-quotes within the string, no?

>  "ab_test1": "This is one of the variations of our split test < img src='1.jpg'>"
