### ISSUE TITLE
Support for analytics.js

### ISSUE THREAD

**Issue by brianpmarks** [danmaz74/ABalytics#8]
The current version doesn't seem to have support for Google's [Universal Analytics](https://developers.google.com/analytics/devguides/collection/analyticsjs/). Would be awesome if it did.

**Comment by danmaz74** [comment]
Hi Brian

Unfortunately I don't have time to work on this for now. Anybody who wanted to contribute would be welcome!

**Comment by dmyers** [comment]
+1

**Comment by gzog** [comment]
I created the #9 pull request a while back that addresses this issue.
